const STATUS_CODE = {
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR',
    FORBIDDEN : 'FORBIDDEN',
    EMAIL_USED: 'EMAIL_USED',
    INCORRECT_USER_NAME: 'INCORRECT_USER_NAME',
    INCORRECT_USER_EMAIL: 'INCORRECT_USER_EMAIL',
    INCORRECT_STUDENT_EMAIL: 'INCORRECT_STUDENT_EMAIL',
    INCORRECT_USER_VISIONS: 'INCORRECT_USER_VISIONS',
    INCORRECT_STATUS: 'INCORRECT_STATUS',
    INCORRECT_TYPE: 'INCORRECT_TYPE',
    ROW_OUT_OF_BOUNDS: 'ROW_OUT_OF_BOUNDS',
    INCORRECT_FY_NAME: 'INCORRECT_FY_NAME',
    INCORRECT_FY_EMAIL: 'INCORRECT_FY_EMAIL',
    INCORRECT_FY_VISIONS: 'INCORRECT_FY_VISIONS',
    UNKNOWN_SORT: 'UNKNOWN_SORT',
    USER_EXIST : 'USER_EXIST',
    //auth
    INVALID_EMAIL : 'INVALID_EMAIL',
    REQUEST_SIGN_UP : 'REQUEST_SIGN_UP',
    INVALID_PASSWORD : 'INVALID_PASSWORD',
    NO_TOKEN : 'NO_TOKEN',
    NOT_VALID_TOKEN:'NOT_VALID_TOKEN',
    //attendance
    INVALID_EVENT: 'INVALID_EVENT',
    INVALID_STUDENT_EVENT: 'INVALID_STUDENT_EVENT',
    INVALID_USER: 'INVALID_USER',
    INVALID_STUDENT: 'INVALID_STUDENT',
    REPEATED_RECORDS: 'REPEATED_RECORDS',
    NO_EXISTING_RECORDS: 'NO_EXISTING_RECORDS',
    //export 
    EMPTY_DATA: 'EMPTY_DATA',
    //event
    INCORRECT_EVENT_ID: 'INCORRECT_EVENT_ID',
    UNAUTHORIZED: 'UNAUTHORIZED',
    INVALID_START_END_TIMES: 'INVALID_START_END_TIMES',
    VISIONS_EXIST: 'VISIONS_EXIST'
}

const SORT_ORDER = {
    ASC: 'ASC',
    DESC: 'DESC'
}

const TYPE = {
    VUCEPTOR: 'vuceptor',
    ADVISER : 'adviser',
    BOARD: 'board'
}

const REGISTRATION_STATUS = {
    REGISTERED: 'registered',
    UNREGISTERED : 'unregistered'
}

const ATTENDANCE = {
    NON_LOGGED:'unlogged',
    ABSENT: 'absent',
    PRESENT: 'present'
}

module.exports = {
    STATUS_CODE,
    SORT_ORDER,
    TYPE,
    ATTENDANCE,
    REGISTRATION_STATUS
}