const STATUS_CODE = {
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR',
    EMAIL_USED: 'EMAIL_USED',
    INCORRECT_USER_NAME: 'INCORRECT_USER_NAME',
    INCORRECT_USER_EMAIL: 'INCORRECT_USER_EMAIL',
    INCORRECT_USER_VISIONS: 'INCORRECT_USER_VISIONS',
    INCORRECT_STATUS: 'INCORRECT_STATUS',
    INCORRECT_TYPE: 'INCORRECT_TYPE',
    ROW_OUT_OF_BOUNDS: 'ROW_OUT_OF_BOUNDS', // need this?
    INCORRECT_FY_NAME: 'INCORRECT_FY_NAME',
    INCORRECT_FY_EMAIL: 'INCORRECT_FY_EMAIL',
    INCORRECT_FY_VISIONS: 'INCORRECT_FY_VISIONS',
    UNKNOWN_SORT: 'UNKNOWN_SORT'
}

const SORT_ORDER = {
    ASC: 'ASC',
    DESC: 'DESC'
}

const TYPE = {
    VUCEPTOR: 'vuceptor',
    ADVISER : 'adviser',
    BOARD: 'board'
}

const REGISTRATION_STATUS = {
    REGISTERED: 'registered',
    UNREGISTERED : 'unregistered'
}

module.exports = {
    STATUS_CODE,
    SORT_ORDER,
    TYPE,
    REGISTRATION_STATUS
}